__all__ = [
    "ARCHITECTURE_STAGES",
    "StageDescriptor",
    "Orchestrator",
    "build_default_orchestrator",
    "ActionDecision",
    "AgentDecision",
    "AgentRoute",
    "AgentState",
    "AutonomyMetrics",
    "AuthContext",
    "AuthMode",
    "Channel",
    "ContextSignal",
    "ContextSnapshot",
    "ControlDecision",
    "ConversationTurn",
    "ExecutionPlan",
    "ExecutionResult",
    "GatewayHeaders",
    "GatewayResult",
    "HandoffPacket",
    "InteractionResponse",
    "MemoryRecord",
    "MemorySnapshot",
    "ModelEvaluationRecord",
    "ModelExecutionRecord",
    "ObservationRecord",
    "PermissionDecision",
    "PermissionMode",
    "PlanStep",
    "RateLimitStatus",
    "ReasoningStep",
    "ReActCycle",
    "ReActStepTrace",
    "RuntimeTrace",
    "ReflectionReport",
    "SafetyPolicyHit",
    "SafetyReport",
    "SessionPermissionState",
    "SessionState",
    "SkillDescriptor",
    "StopDecision",
    "StateTransition",
    "StructuredResponse",
    "TaskGraph",
    "TaskNode",
    "StepTrace",
    "ToolAuditMetadata",
    "ToolRequest",
    "ToolSelectionDecision",
    "ToolResult",
    "ToolVerificationResult",
    "TraceEvent",
    "UserRequest",
    "VerificationCheck",
    "VerificationResult",
    "VerificationReport",
    "WorkingMemory",
]


def __getattr__(name: str):
    if name in {"Orchestrator", "build_default_orchestrator"}:
        from .factory import Orchestrator, build_default_orchestrator

        return {
            "Orchestrator": Orchestrator,
            "build_default_orchestrator": build_default_orchestrator,
        }[name]
    if name in {"ARCHITECTURE_STAGES", "StageDescriptor"}:
        from .workflow import ARCHITECTURE_STAGES, StageDescriptor

        return {
            "ARCHITECTURE_STAGES": ARCHITECTURE_STAGES,
            "StageDescriptor": StageDescriptor,
        }[name]
    if name in {
        "ActionDecision",
        "AgentDecision",
        "AgentRoute",
        "AgentState",
        "AutonomyMetrics",
        "AuthContext",
        "AuthMode",
        "Channel",
        "ContextSignal",
        "ContextSnapshot",
        "ControlDecision",
        "ConversationTurn",
        "ExecutionPlan",
        "ExecutionResult",
        "GatewayHeaders",
        "GatewayResult",
        "HandoffPacket",
        "InteractionResponse",
        "MemoryRecord",
        "MemorySnapshot",
        "ModelEvaluationRecord",
        "ModelExecutionRecord",
        "ObservationRecord",
        "PermissionDecision",
        "PermissionMode",
        "PlanStep",
        "RateLimitStatus",
        "ReasoningStep",
        "ReActCycle",
        "ReActStepTrace",
        "RuntimeTrace",
        "ReflectionReport",
        "SafetyPolicyHit",
        "SafetyReport",
        "SessionPermissionState",
        "SessionState",
        "SkillDescriptor",
        "StopDecision",
        "StateTransition",
        "StructuredResponse",
        "TaskGraph",
        "TaskNode",
        "StepTrace",
        "ToolAuditMetadata",
        "ToolRequest",
        "ToolSelectionDecision",
        "ToolResult",
        "ToolVerificationResult",
        "TraceEvent",
        "UserRequest",
        "VerificationCheck",
        "VerificationResult",
        "VerificationReport",
        "WorkingMemory",
    }:
        from . import models as runtime_models

        return getattr(runtime_models, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
