__all__ = [
    "ClaimRecord",
    "ClaimVerificationReport",
    "EvidenceLink",
    "ApprovalState",
    "BrowserGoal",
    "BrowserStateSnapshot",
    "BrowserVerificationResult",
    "HandoffPacket",
    "HandoffSummary",
    "OpenQuestion",
    "Channel",
    "ConversationTurn",
    "AgentCatalog",
    "AgentDescriptor",
    "AuditEvent",
    "AuditLogResponse",
    "GatewayHeaders",
    "InteractionResponse",
    "SessionState",
    "UserRequest",
    "MemoryRecord",
    "MemorySnapshot",
    "SessionPermissionState",
    "ControlDecision",
    "ExecutionPlan",
    "PlanStep",
    "ReActCycle",
    "TaskGraph",
    "HealthResponse",
    "ArchitectureResponse",
    "ArchitectureDecision",
    "ArchitectureReasoning",
    "ArchitectureMode",
    "TaskCharacteristics",
    "AutonomyMetrics",
    "ChatRequest",
    "ChatResponse",
    "ApprovalRiskState",
    "PlanRequest",
    "PlanResponse",
    "ContextMemorySlice",
    "ContextPacket",
    "ExecuteRequest",
    "ExecuteResponse",
    "LoopPhase",
    "LoopState",
    "NormalizedUserRequest",
    "ProviderRouteHint",
    "ProviderRoutingHints",
    "ToolAvailabilitySnapshot",
    "ToolCapability",
    "ToolCatalog",
    "ToolDescriptor",
    "ToolRequest",
    "ToolResult",
    "EvaluationSummary",
    "ModelProvider",
    "ModelTaskType",
    "PlannerOutput",
    "PlannerSubtask",
    "ProviderEvaluationResult",
    "ProviderHealth",
    "ProviderMessage",
    "ProviderRequest",
    "ProviderResponse",
    "RuntimeTrace",
    "ReflectionOutput",
    "RiskLevel",
    "AdaptiveRoutingDecision",
    "HistoricalRoutingStats",
    "RoutingDecision",
    "RoutingPolicyEntry",
    "RoutingScore",
    "RoutingRequest",
    "TaskFamilyRoutingWinner",
    "StepTrace",
    "StructuredOutputSchema",
]


_EXPORTS = {
    "ClaimRecord": ("claims", "ClaimRecord"),
    "ClaimVerificationReport": ("claims", "ClaimVerificationReport"),
    "ApprovalState": ("context", "ApprovalState"),
    "AgentCatalog": ("catalog", "AgentCatalog"),
    "AgentDescriptor": ("catalog", "AgentDescriptor"),
    "ApprovalRiskState": ("adaptive", "ApprovalRiskState"),
    "ArchitectureDecision": ("adaptive", "ArchitectureDecision"),
    "ArchitectureReasoning": ("adaptive", "ArchitectureReasoning"),
    "ArchitectureMode": ("adaptive", "ArchitectureMode"),
    "ArchitectureResponse": ("platform", "ArchitectureResponse"),
    "AutonomyMetrics": ("observability", "AutonomyMetrics"),
    "AdaptiveRoutingDecision": ("routing", "AdaptiveRoutingDecision"),
    "AuditEvent": ("catalog", "AuditEvent"),
    "AuditLogResponse": ("catalog", "AuditLogResponse"),
    "BrowserGoal": ("browser", "BrowserGoal"),
    "BrowserStateSnapshot": ("browser", "BrowserStateSnapshot"),
    "BrowserVerificationResult": ("browser", "BrowserVerificationResult"),
    "HandoffPacket": ("handoff", "HandoffPacket"),
    "HandoffSummary": ("handoff", "HandoffSummary"),
    "OpenQuestion": ("handoff", "OpenQuestion"),
    "Channel": ("chat", "Channel"),
    "ChatRequest": ("platform", "ChatRequest"),
    "ChatResponse": ("platform", "ChatResponse"),
    "ControlDecision": ("plan", "ControlDecision"),
    "ContextMemorySlice": ("context", "ContextMemorySlice"),
    "ContextPacket": ("context", "ContextPacket"),
    "ConversationTurn": ("chat", "ConversationTurn"),
    "EvaluationSummary": ("evaluation", "EvaluationSummary"),
    "EvidenceLink": ("claims", "EvidenceLink"),
    "ExecuteRequest": ("platform", "ExecuteRequest"),
    "ExecuteResponse": ("platform", "ExecuteResponse"),
    "ExecutionPlan": ("plan", "ExecutionPlan"),
    "GatewayHeaders": ("chat", "GatewayHeaders"),
    "HealthResponse": ("platform", "HealthResponse"),
    "HistoricalRoutingStats": ("routing", "HistoricalRoutingStats"),
    "InteractionResponse": ("chat", "InteractionResponse"),
    "MemoryRecord": ("memory", "MemoryRecord"),
    "MemorySnapshot": ("memory", "MemorySnapshot"),
    "ModelProvider": ("routing", "ModelProvider"),
    "ModelTaskType": ("routing", "ModelTaskType"),
    "LoopPhase": ("adaptive", "LoopPhase"),
    "LoopState": ("adaptive", "LoopState"),
    "NormalizedUserRequest": ("context", "NormalizedUserRequest"),
    "PlanRequest": ("platform", "PlanRequest"),
    "PlanResponse": ("platform", "PlanResponse"),
    "PlanStep": ("plan", "PlanStep"),
    "PlannerOutput": ("planner", "PlannerOutput"),
    "PlannerSubtask": ("planner", "PlannerSubtask"),
    "ProviderRouteHint": ("context", "ProviderRouteHint"),
    "ProviderRoutingHints": ("context", "ProviderRoutingHints"),
    "ProviderEvaluationResult": ("evaluation", "ProviderEvaluationResult"),
    "ProviderHealth": ("provider", "ProviderHealth"),
    "ProviderMessage": ("provider", "ProviderMessage"),
    "ProviderRequest": ("provider", "ProviderRequest"),
    "ProviderResponse": ("provider", "ProviderResponse"),
    "RuntimeTrace": ("observability", "RuntimeTrace"),
    "ReActCycle": ("plan", "ReActCycle"),
    "ReflectionOutput": ("reflection", "ReflectionOutput"),
    "RiskLevel": ("planner", "RiskLevel"),
    "RoutingDecision": ("routing", "RoutingDecision"),
    "RoutingPolicyEntry": ("routing", "RoutingPolicyEntry"),
    "RoutingScore": ("routing", "RoutingScore"),
    "RoutingRequest": ("routing", "RoutingRequest"),
    "TaskFamilyRoutingWinner": ("routing", "TaskFamilyRoutingWinner"),
    "SessionPermissionState": ("memory", "SessionPermissionState"),
    "SessionState": ("chat", "SessionState"),
    "StepTrace": ("observability", "StepTrace"),
    "StructuredOutputSchema": ("provider", "StructuredOutputSchema"),
    "TaskGraph": ("plan", "TaskGraph"),
    "TaskCharacteristics": ("adaptive", "TaskCharacteristics"),
    "ToolAvailabilitySnapshot": ("context", "ToolAvailabilitySnapshot"),
    "ToolCapability": ("context", "ToolCapability"),
    "ToolCatalog": ("catalog", "ToolCatalog"),
    "ToolDescriptor": ("catalog", "ToolDescriptor"),
    "ToolRequest": ("tool", "ToolRequest"),
    "ToolResult": ("tool", "ToolResult"),
    "UserRequest": ("chat", "UserRequest"),
}


def __getattr__(name: str):
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _EXPORTS[name]
    module = __import__(f"{__name__}.{module_name}", fromlist=[attr_name])
    return getattr(module, attr_name)
