[theme]
base = "dark"
primaryColor = "#A9BEE6"
backgroundColor = "#04080D"
secondaryBackgroundColor = "#0D141C"
textColor = "#E7EDF5"
font = "serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
